global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ceph'
    static_configs:
      - targets: ['ceph-mgr:9283']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ceph-cluster'
